#!/bin/bash

set -e

PRODUCT=aTES
BASE_NAME=task-tracker
VENV_DIR=/opt/algont/${PRODUCT}/venv/${BASE_NAME}-venv

if [ "$1" = "remove" ] || [ "$1" = "purge" ]; then
    rm -rf $VENV_DIR
    rm -rf /var/log/${PRODUCT}/$BASE_NAME
fi
