#!/bin/bash

BASE_NAME=task-tracker

{
    echo "Stopping the service"
    supervisorctl stop $BASE_NAME
} || {
    echo "Can not stop the service"
}

{
    echo "Removing the service"
    supervisorctl remove $BASE_NAME
} || {
    echo "Can not remove the service"
}
